image: Visual Studio 2022
build: off
skip_commits:
  files:
  - '**/*.md'
  - '.vscode/**/*'
cache:
- '%USERPROFILE%\Documents\WindowsPowerShell\Modules -> .appveyor.yml'
environment:
  SCOOP: C:\projects\scoop
  SCOOP_HOME: C:\projects\scoop\apps\scoop\current
  matrix:
  - PowerShell: 5
  - PowerShell: 7
init:
- ps: |
    (Get-PSProvider 'FileSystem').Home = 'C:\projects'
    if (!(Test-Path "$env:SCOOP_HOME")) { git clone --quiet --depth=1 "https://github.com/Ash258/Scoop-Core" "$env:SCOOP_HOME" }
matrix:
  fast_finish: true
for:
- matrix:
    only:
    - PowerShell: 5
  install:
  - ps: . "$env:SCOOP_HOME\test\bin\init.ps1"
  test_script:
  - ps: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
- matrix:
    only:
    - PowerShell: 7
  install:
  - pwsh: . "$env:SCOOP_HOME\test\bin\init.ps1"
  test_script:
  - pwsh: . "$env:SCOOP_HOME\test\bin\test.ps1" -TestPath "$env:APPVEYOR_BUILD_FOLDER"
